In [20]:
import seaborn as sns
from  pandas import read_csv
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2,f_regression
dataframe=sns.load_dataset('tips')
dataframe

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [23]:
from sklearn.preprocessing import LabelEncoder
lb=LabelEncoder()
dataframe['smoker']=lb.fit_transform(dataframe['smoker'])

dataframe['sex']=lb.fit_transform(dataframe['sex'])

dataframe['time']=lb.fit_transform(dataframe['time'])

dataframe['day']=lb.fit_transform(dataframe['day'])
dataframe

total_bill   tip  sex  smoker  day  time  size
0         16.99  1.01    0       0    2     0     2
1         10.34  1.66    1       0    2     0     3
2         21.01  3.50    1       0    2     0     3
3         23.68  3.31    1       0    2     0     2
4         24.59  3.61    0       0    2     0     4
..          ...   ...  ...     ...  ...   ...   ...
239       29.03  5.92    1       0    1     0     3
240       27.18  2.00    0       1    1     0     2
241       22.67  2.00    1       1    1     0     2
242       17.82  1.75    1       0    1     0     2
243       18.78  3.00    0       0    3     0     2

[244 rows x 7 columns]

In [24]:
X= dataframe.iloc[:,1:]
Y= dataframe.iloc[:,0]

In [25]:
 X

tip  sex  smoker  day  time  size
0    1.01    0       0    2     0     2
1    1.66    1       0    2     0     3
2    3.50    1       0    2     0     3
3    3.31    1       0    2     0     2
4    3.61    0       0    2     0     4
..    ...  ...     ...  ...   ...   ...
239  5.92    1       0    1     0     3
240  2.00    0       1    1     0     2
241  2.00    1       1    1     0     2
242  1.75    1       0    1     0     2
243  3.00    0       0    3     0     2

[244 rows x 6 columns]

In [26]:
Y

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...  
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [27]:
X = dataframe.drop('tip',axis=1)
Y = dataframe.tip

In [28]:
X

total_bill  sex  smoker  day  time  size
0         16.99    0       0    2     0     2
1         10.34    1       0    2     0     3
2         21.01    1       0    2     0     3
3         23.68    1       0    2     0     2
4         24.59    0       0    2     0     4
..          ...  ...     ...  ...   ...   ...
239       29.03    1       0    1     0     3
240       27.18    0       1    1     0     2
241       22.67    1       1    1     0     2
242       17.82    1       0    1     0     2
243       18.78    0       0    3     0     2

[244 rows x 6 columns]

In [29]:
Y

0      1.01
1      1.66
2      3.50
3      3.31
4      3.61
       ... 
239    5.92
240    2.00
241    2.00
242    1.75
243    3.00
Name: tip, Length: 244, dtype: float64

In [34]:
test=SelectKBest(score_func=f_regression, k=3).fit(X,Y)
test

SelectKBest(k=3, score_func=<function f_regression at 0x0000022C8E2642C0>)

In [35]:
test.scores_

array([2.03357723e+02, 1.92615456e+00, 8.50601355e-03, 3.22744400e-02,
       3.63381548e+00, 7.61754260e+01])

In [40]:
np.around(test.scores_,2)

array([2.0336e+02, 1.9300e+00, 1.0000e-02, 3.0000e-02, 3.6300e+00,
       7.6180e+01])

In [39]:
np.around(test.pvalues_,3)

array([0.   , 0.166, 0.927, 0.858, 0.058, 0.   ])

In [41]:
dataframe.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [42]:
dataframe.columns[test.get_support(indices=True)]

Index(['total_bill', 'day', 'time'], dtype='object')

In [43]:
dataframe.columns[np.where(test.pvalues_>0.05)]

Index(['tip', 'sex', 'smoker', 'day'], dtype='object')

In [45]:
df=sns.load_dataset('iris')
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [46]:
df['iris']=lb.fit_transform(df['species'])

In [47]:
df.head()

sepal_length  sepal_width  petal_length  petal_width species  iris
0           5.1          3.5           1.4          0.2  setosa     0
1           4.9          3.0           1.4          0.2  setosa     0
2           4.7          3.2           1.3          0.2  setosa     0
3           4.6          3.1           1.5          0.2  setosa     0
4           5.0          3.6           1.4          0.2  setosa     0

In [48]:
x=df.iloc[:,0:4]

In [49]:
x

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [50]:
y=df['species']

In [52]:
d=SelectKBest(score_func=chi2,k=2).fit(x,y)
d

SelectKBest(k=2, score_func=<function chi2 at 0x0000022C8E264040>)

In [56]:
d.pvalues_

array([4.47651499e-03, 1.56395980e-01, 5.53397228e-26, 2.75824965e-15])

In [57]:
d.scores_

array([ 10.81782088,   3.7107283 , 116.31261309,  67.0483602 ])

In [59]:
df.columns[np.where(d.get_support(indices=True))]

Index(['sepal_length', 'sepal_width'], dtype='object')