In [2]:
import pandas as pd

In [3]:
df=pd.read_csv(r"C:\Users\ASHOK REDDY\Downloads\diabetes.csv")
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [4]:
df.drop(['Glucose','SkinThickness','DiabetesPedigreeFunction','Outcome'],axis=1,inplace=True)

In [5]:
df

Pregnancies  BloodPressure  Insulin   BMI  Age
0              6             72        0  33.6   50
1              1             66        0  26.6   31
2              8             64        0  23.3   32
3              1             66       94  28.1   21
4              0             40      168  43.1   33
..           ...            ...      ...   ...  ...
763           10             76      180  32.9   63
764            2             70        0  36.8   27
765            5             72      112  26.2   30
766            1             60        0  30.1   47
767            1             70        0  30.4   23

[768 rows x 5 columns]

In [8]:
df.drop([763,764,765,766],axis=0,inplace=True)

In [9]:
df

Pregnancies  BloodPressure  Insulin   BMI  Age
0              6             72        0  33.6   50
1              1             66        0  26.6   31
2              8             64        0  23.3   32
3              1             66       94  28.1   21
4              0             40      168  43.1   33
..           ...            ...      ...   ...  ...
759            6             92        0  35.5   66
760            2             58       16  28.4   22
761            9             74        0  44.0   43
762            9             62        0  22.5   33
767            1             70        0  30.4   23

[764 rows x 5 columns]

In [10]:
df.head()

Pregnancies  BloodPressure  Insulin   BMI  Age
0            6             72        0  33.6   50
1            1             66        0  26.6   31
2            8             64        0  23.3   32
3            1             66       94  28.1   21
4            0             40      168  43.1   33

In [17]:
df.tail(666)

Pregnancies  BloodPressure  Insulin   BMI  Age
98             6             50       64  28.7   23
99             1             90      220  49.7   31
100            1             72        0  39.0   33
101            1             60        0  26.1   22
102            0             96        0  22.5   21
..           ...            ...      ...   ...  ...
759            6             92        0  35.5   66
760            2             58       16  28.4   22
761            9             74        0  44.0   43
762            9             62        0  22.5   33
767            1             70        0  30.4   23

[666 rows x 5 columns]

In [19]:
df.tail(10)

Pregnancies  BloodPressure  Insulin   BMI  Age
754            8             78        0  32.4   45
755            1             88      110  36.5   37
756            7             90        0  32.0   39
757            0             72        0  36.3   52
758            1             76        0  37.5   26
759            6             92        0  35.5   66
760            2             58       16  28.4   22
761            9             74        0  44.0   43
762            9             62        0  22.5   33
767            1             70        0  30.4   23

In [23]:
df=pd.read_csv(r"C:\Users\ASHOK REDDY\Downloads\diabetes.csv")
df=pd.read_excel(r"C:\Users\ASHOK REDDY\Downloads\Data-for-Practice.xlsx")
df

Unnamed: 0                             Unnamed: 1 Unnamed: 2 Unnamed: 3  \
0          NaN  Excel Data for Practice Free Download        NaN        NaN   
1          NaN                                    NaN        NaN        NaN   
2          NaN                                   Date  Sales Rep      Shift   
3          NaN                    2022-07-01 00:00:00        Ben      Night   
4          NaN                    2022-07-01 00:00:00      Jacob        Day   
..         ...                                    ...        ...        ...   
86         NaN                    2022-08-29 00:00:00      Jacob        Day   
87         NaN                    2022-08-30 00:00:00        Ben        Day   
88         NaN                    2022-08-30 00:00:00      Jacob      Night   
89         NaN                    2022-08-31 00:00:00        Ben      Night   
90         NaN                    2022-08-31 00:00:00      Jacob        Day   

    Unnamed: 4     Unnamed: 5 Unnamed: 6 Unnamed: 7  Unnamed: 8 Unnamed: 9  
0          NaN            NaN        NaN        NaN         NaN        NaN  
1          NaN            NaN        NaN        NaN         NaN        NaN  
2   Cost Price  Selling Price     Profit   Profit %  Commission    Weekday  
3      1112.94           1288        NaN        NaN         NaN        NaN  
4       1095.5        1250.75        NaN        NaN         NaN        NaN  
..         ...            ...        ...        ...         ...        ...  
86       774.2         946.25        NaN        NaN         NaN        NaN  
87     1350.48         1509.5        NaN        NaN         NaN        NaN  
88     1053.37        1136.25        NaN        NaN         NaN        NaN  
89     1161.92           1237        NaN        NaN         NaN        NaN  
90      951.93           1136        NaN        NaN         NaN        NaN  

[91 rows x 10 columns]

In [28]:
dataset_house=pd.read_csv("C:\Users\ASHOK REDDY\Downloads\diabetes.csv",sheet_name="diabetes.csv")
dataset_house

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (465721658.py, line 1)

In [29]:
import os
os.getcwd()

'C:\\Users\\ASHOK REDDY'

In [30]:
import numpy as np

In [35]:
a=np.zeros(9)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [36]:
type(a)

numpy.ndarray

In [37]:
type(a[0])

numpy.float64

In [38]:
z=np.zeros(10)

In [41]:
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [46]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [49]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [53]:
z=np.empty(3)
z

array([1.25266586e-311, 0.00000000e+000, 6.95250702e-310])

In [55]:
z=np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [56]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])

In [57]:
z=np.array([10,20])
z

array([10, 20])